spring.application.name=EmployeePayrollApplication


# =========================================================
# SERVER
# =========================================================

server.port=8080


# =========================================================
# POSTGRESQL DATABASE CONFIGURATION
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_payroll_db
spring.datasource.username=postgres
spring.datasource.password=navya1017

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / HIBERNATE CONFIGURATION
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# HIKARI CONNECTION POOL
# =========================================================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


# =========================================================
# LOGGING
# =========================================================

logging.level.org.springframework=INFO
logging.level.com.bridgelabz=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE